apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  annotations:
    tekton.dev/git-0: gitlab.example.com
    tekton.dev/git-1: github.com
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: <base64>
  known_hosts: <base64>
  config: SG9zdCBnaXRodWIuY29tCiAgICBIb3N0TmFtZSBnaXRodWIuY29tCiAgICBJZGVudGl0eUZpbGUgfi8uc3NoL3NzaC1wcml2YXRla2V5
